language: go

go:
  - 1.10.2
  - tip

before_install:
  - go get -t -v ./...

install: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/golang/dep/cmd/dep		# dependency check -> dep init
  - go get -u github.com/PuerkitoBio/goquery
  - dep ensure									

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
  - ./codecov.sh
  - golint -set_exit_status $(go list ./...)

after_success:
  - bash <(curl -s https://codecov.io/bash)
